name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'  # Trigger only when pushing git tags prefixed with 'v'.

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Extract version from tag
        id: get_version
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          echo "PACKAGE_VERSION=$TAG" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore Sog.Analyzers.Package/Sog.Analyzers.Package.csproj

      - name: Build
        run: dotnet build Sog.Analyzers.Package/Sog.Analyzers.Package.csproj --configuration Release --no-restore

      - name: Pack
        run: |
          dotnet pack Sog.Analyzers.Package/Sog.Analyzers.Package.csproj \
            --configuration Release \
            --no-build \
            --output ./nupkg \
            /p:PackageVersion=${{ env.PACKAGE_VERSION }}

      - name: Push to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
